# -*- coding: utf-8 -*-
{
    'name': 'Gestión de Digitalización',
    'version': '17.0.1.0.0',
    'category': 'Services',
    'summary': 'Gestión de proyectos de digitalización de documentos',
    'author': 'Jimena Castro — Práctica Profesional OTEC GLOBAL',
    'depends': ['base', 'contacts', 'website'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/etapas_default.xml',
        'views/admin/menu_views.xml',
        'views/admin/proyecto_views.xml',
        'views/admin/asignacion_views.xml',
        'views/operaciones/miembro_views.xml',
        'views/operaciones/registro_views.xml',
        'views/configuracion/etapa_views.xml',
        'views/configuracion/tipo_escaner_views.xml',
        'views/portal/portal_home.xml',
        'views/portal/portal_proyecto.xml',
        'views/portal/portal_registro_form.xml',
        'views/portal/portal_miembros.xml',
        'views/dashboard/dashboard_admin.xml',
        'wizard/cambio_etapa_wizard_views.xml',
        'wizard/asignacion_rapida_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
